### ISSUE TITLE
ToDo list :)

### ISSUE THREAD

**Issue by tomvanmele** [compas-dev/compas_viewer#191]
Feel free to add other stuff

* [ ] Details of selected scene object in sidebar, in designated area below
* [ ] Easier-to-use controls for scene object details. For example, horizontal slider for opacity instead of spinner
* [ ] Change visibility of entire groups of objects in tree view
* [ ] Maintain state of tree view before, during, after other commands: if it is expanded, it should stay expanded, ...
* [ ] Separate widget for viewing/editing data item of scene object, with separate tabs for essential data and general attributes if any.
* [ ] Widget for editing data of components of data structures. For example, for a mesh there should be a (table) widget with a tab for vertices, edges, and faces listing the data attributes of the individual elements.
* [ ] Save current state to file (including all modified data)

**Comment by PingHsunTsai** [comment]
Hi @tomvanmele, we just finished a PR with object setting with @Licini.
Regarding your points above,  some of them have already been implemented(clicked).  Correct me if I'm wrong Li.

I can start working on separated tab data editing widget for mesh.
Just have one question, what do you mean separate viewing/editing data item of scene object? like color is in viewing tab and opacity is editing tab?
